bundle/manifests/backstage-default-config_v1_configmap.yaml, config/manager/default-config/deployment.yaml, integration_tests/rhdh-config_test.go, pkg/model/deployment_test.go, pkg/model/dynamic-plugins_test.go, pkg/model/testdata/janus-deployment.yaml
For secure container registry we need a `auth.json` file that contains auth tokens. The file is stored as a secret like
```
oc create secret generic dynamic-plugins-registry-auth --from-file=~/.config/containers/auth.json
```
It is then picked up by `skopeo` during the dynamic plugin install process.
Accompanying PR for dynamic plugins:
https://github.com/janus-idp/backstage-showcase/pull/1479
https://github.com/redhat-developer/rhdh-chart/pull/41
=> add dynamic-plugins-registry-auth secret

.github/renovate.json
chore: suspend updating github.com/openshift/* on renovate till UBI go 1.22
=> chore: suspend updating github.com/openshift/* on renovate

.github/workflows/next-container-build.yaml
The nightly Workflow passes but with a warning on 1.2.x about a missing [`quay.io/rhdh-community/operator:0.2.3`](http://quay.io/rhdh-community/operator:0.2.3) image tag. Example: https://github.com/redhat-developer/rhdh-operator/actions/runs/10624194874
These warnings can be expected since CI tags purposely expire after a few weeks. But in this specific case, we should have recent image builds from the 1.2.x branch because that branch has been updated recently.
It looks like the job building and pushing that image on 1.2.x did not pass: https://github.com/redhat-developer/rhdh-operator/actions/runs/10620716428/job/29441095997
```
Successfully tagged quay.io/rhdh-community/operator-catalog:0.2.3
28bce337c49efa5435c24f607dad615f4bd0ffa4f026175b896dc81ce0e43749
+ for image in operator …
```
=> [1.2.x] ci: Fix image repo location when pushing operator images

docs/configuration.md
This caused some of the YAML examples to be wrongly formatted, e.g.:
Reported in https://redhat-internal.slack.com/archives/C04CUSD4JSG/p1725615442856339
&mdash;
=> docs: fix indentation in configuration doc

.github/renovate.json
Disable renovate updates to kustomize because `newTags` are not being updated properly.  They are being bumped to the latest minor version in each branch which is not what we want.   Seems like updates are being done manually now today.  This change will make it easier to merge the renovate PRs
https://issues.redhat.com/browse/RHIDP-4007
=> chore(deps): disable kustomize updates

.github/workflows/renovate-checks.yaml
While reviewing https://github.com/redhat-developer/rhdh-operator/pull/185, I thought it could help to check the Renovate config file in CI (for PRs that modify the config file). And I quickly found that there is a standalone tool from Renovate that could allow us to enforce such checks - see https://docs.renovatebot.com/config-validation/.
(If that makes sense).
&mdash;
If you have the [`act`](https://github.com/nektos/act) and [`gh`](https://cli.github.com/) CLIs locally, you can run this job locally with `gh act -j renovate-config-validator`
/cc @kim-tsao @nickboldt
=> ci: Validate Renovate config in CI

.github/workflows/nightly.yaml
This includes the `1.3.x` branch in the branches against which the E2E nightly tests should run.
&mdash;
&mdash;
=> ci: Run E2E tests against the `1.3.x` branch

.github/workflows/nightly.yaml, .gitignore, tests/e2e/e2e_upgrade_test.go, tests/e2e/testdata/rhdh-operator-1.1.yaml
More context in https://issues.redhat.com/browse/RHIDP-4066.
The content in `tests/e2e/testdata/backstage-operator-0.1.3.yaml`
used to deploy a "Backstage" operator as it looks like in 1.1.x,
but `main` now deploys an `RHDH` profile by default instead,
hence the mismatch.
Right now, we just want to test the upgrade using the default
behavior we had in the previous version, which is now
the 'RHDH' profile. So this renames the `testdata` manifest
to a more specific RHDH manifest, as this is what was actually
being expected anyway.
- Fixes https://issues.redhat.com/browse/RHIDP-4066
`make test-e2e-upgrade`  should work from the `main` branch.
=> ci: Fix the 'Upgrade' E2E tests on `main` [RHIDP-4066]

.github/renovate.json
We are not going to do any more 1.1.x releases and we are now using the release-1.3 branch instead of 1.3.x so this pull request updates the configuration to not include those branches in the renovate generated pull requests.
=> Do not include the 1.1.x or 1.3.x branches in renovate

docker/Dockerfile
https://issues.redhat.com/browse/RHIDP-3173
=> chore: [1.2.x] bump go-toolset to 1.21.13 in Dockerfile

docker/Dockerfile
https://issues.redhat.com/browse/RHIDP-4031
=> chore: [release-1.3] bump go-toolset to 1.21.13 in Dockerfile

.github/workflows/nightly.yaml, tests/e2e/e2e_upgrade_test.go, tests/e2e/testdata/rhdh-operator-1.2.yaml
This removes the nightly tests against the 1.1.x branch (and especially upgrade tests from 1.1). Instead, the baseline for the operator upgrade tests is now the 1.2.x branch.
With the upcoming 1.3 release, 1.1.x will no longer be supported.
Relates to https://issues.redhat.com/browse/RHIDP-2641
Example run: https://github.com/rm3l/redhat-developer-hub-operator/actions/runs/11123310353
=> ci(nightly): Use 1.2.x as baseline for the operator upgrade tests

.rhdh/bundle/manifests/rhdh-operator.csv.yaml, Makefile, bundle/manifests/backstage-operator.clusterserviceversion.yaml
=> chore: tagRelease.sh: bump to 1.3.1 in release-1.3 branch

.github/renovate.json
We were getting a lot of noise from dependency updates for the following modules, which all require Go 1.22+ (not yet supported at the moment).
We usually end up manually closing the corresponding PRs, but new ones would be created as soon as there were new updates available.
The ones from `github.com/openshift/api` were creating most of the noise because we are depending on a pseudo-version mapped to a commit. So (from my observations) a new update PR would be created anytime there is a new commit in https://github.com/openshift/api/commits/master/.
- https://github.com/redhat-developer/rhdh-operator/pulls?q=sort%3Acreated-desc+is%3Apr+%22github.com%2Fopenshift%2Fapi%22+is%3Aclosed+
- https://github.com/redhat-developer/rhdh-operator/pulls?q=sort%3Acreated-desc+is%3Apr+%22github.com%2Fons …
=> chore(deps): make sure Renovate updates for OpenShift, Ginkgo and Gomega modules are disabled

bundle/manifests/backstage-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/backstage-operator.clusterserviceversion.yaml
This is an addendum to https://github.com/redhat-developer/rhdh-operator/pull/318.
I noticed that some Renovate PRs updating simple Github Actions resulted in changes in the bundle - see https://github.com/redhat-developer/rhdh-operator/pull/323/files#diff-350e6729515e8cd74b357c91611b67dc4e9723daa6863854a252fc6acea032cf
&mdash;
/cc @nickboldt
=> chore: fix versions in bundle config and regenerate bundle [release-1.3]

README.md, docs/configuration.md
Noticed the dynamic-plugins and Telemetry data collection links navigate the reader to a 404 Page Not Found, this PR seeks to fix this.
=> chore(fixup): Updating README links

examples/rhdh-cr-with-app-configs.yaml
Some Technical Preview plugins are no longer enabled by default in RHDH 1.3+, and need to be explicitly enabled.
Ref: https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.3/html/release_notes/breaking-changes
```
[...]
[FAILED] Timed out after 300.054s.                                                                                                                                                           
The function passed to Eventually failed at /home/asoro/work/projects/backstage/janus-idp/operator/tests/helper/helper_backstage.go:176 with:                                                
context: /api/dynamic-plugins-info/loaded-plugins …
```
=> Fix the E2E tests against OCP [RHIDP-4499]

.rhdh/docs/installing-ci-builds.adoc, .rhdh/scripts/install-rhdh-catalog-source.sh
This PR makes the `.rhdh/scripts/install-rhdh-catalog-source.sh` script detect whether the OCP cluster it is running against has a hosted control plane (HyperShift, ROSA, IBM Cloud, ...) and adapts its behavior accordingly.
In such a situation where the control plane is hosted, we cannot actually rely on the ImageContentSourcePolicy/ImageDigestMirrorSet, which will be created but won't be propagated to the cluster nodes.
As a workaround, this script rebuilds a new index by replacing all references to the internal registries with their equivalents on quay.io. It also does the same thing with the operator bundles, because the manifests in them might also contain references to internal registries. It pushes those new images into the internal cluster image registry.
#82 provided a similar …
=> Make the CI builds install script able to detect and work against clusters with hosted control planes

.rhdh/bundle/manifests/rhdh-operator.csv.yaml, Makefile, bundle/manifests/backstage-operator.clusterserviceversion.yaml
=> chore: tagRelease.sh: bump to 1.3.2 in release-1.3 branch

bundle/backstage.io/manifests/backstage-default-config_v1_configmap.yaml, bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/rhdh-default-config_v1_configmap.yaml, config/profile/backstage.io/default-config/service.yaml, config/profile/rhdh/default-config/service.yaml
Exposes an extra port (9464) in the backstage service for the Backstage metrics
[RHIDP-5005](https://issues.redhat.com/browse/RHIDP-5005)
Install the ServiceMonitor manually, and Backstage metrics will appear under `Observe` > `Metrics`
```
$ CR_NAME=bs1
$ MY_PROJECT=rhdh-test
$ cat <<EOF > /tmp/${CR_NAME}.ServiceMonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
name: ${CR_NAME}
namespace: ${MY_PROJECT}
labels:
app.kubernetes.io/instance: ${CR_NAME}
app.kubernetes.io/name: backstage
spec:
namespaceSelector:
matchNames:
- ${MY_PROJECT}
selector:
matchLabels:
app.kubernetes.io/instance: ${CR_NAME}
app.kubernetes.io/name: backstage
endpoints:
- port: http-metrics
path: /metrics
EOF
$ oc apply -f /tmp/${CR_NAME}.ServiceMonitor.yaml
```
=> feat: add support for exposing OpenTelemetry metrics port

.rhdh/docs/installing-ci-builds.adoc, .rhdh/scripts/install-rhdh-catalog-source.sh
In Prow CI containers, it appears that Podman could not be used due to a restricted environment.
The error below was returned:
```
[...]
[DEBUG] registry.redhat.io/rhdh/rhdh-operator-bundle@sha256:2abaeacfa8fd744579e44e4b320086a8678094dd92eb24825c05f43617384529 => quay.io/rhdh/rhdh-operator-bundle@sha256:2abaeacfa8fd744579e44e4b320086a8678094dd92eb24825c05f43617384529
time="2024-11-14T08:04:54Z" level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers"
cannot clone: Operation not permitted
Error: cannot re-exec process
[...]
```
This PR removes the need for Podman to build and push the images. Instead, it now leverages both umoci [1] and Skopeo to manipulate the images, rebuild and repush them in the internal cluster registry.
[1] …
=> [RHIDP-4934] Fix issue preventing the CI install script from being used in restricted systems where Podman would not work

bundle/manifests/backstage-default-config_v1_configmap.yaml, bundle/manifests/backstage-operator.clusterserviceversion.yaml, config/manager/default-config/deployment.yaml, config/manager/kustomization.yaml, config/manifests/bases/backstage-operator.clusterserviceversion.yaml, tests/e2e/e2e_test.go
The nightly checks have been failing recently (especially the job against the `release-1.3` branch). See https://github.com/redhat-developer/rhdh-operator/actions/runs/12000574475/job/33449852746
It turns out that we are using the `next` RHDH tag, which now seems to require a new mandatory `auth.providers` field in the app-config (added recently in the `main` branches for both [Helm](https://github.com/redhat-developer/rhdh-chart/pull/46/files#diff-8060d9a38501197eddb026fced7fe56f104f4f5143210c6d47781b831a7097f4) and the [Operator](https://github.com/redhat-developer/rhdh-operator/pull/393/files#diff-4c1e3001a09525c00affd3f7eaf28970ecbe52bc189532ad34731b604cbd31f9)).
This PR makes sure to use the 1.3 RHDH tag in the release-1.3 branch by default.
With hindsight, I think that, going …
=> fix(release-1.3): Fix the E2E tests on `release-1.3`

go.mod, go.sum, tests/e2e/e2e_test.go, tests/helper/helper_backstage.go
The E2E nightly jobs would fail because the list of dynamic plugins had changed in the `next` RHDH tag the operator uses by default.
To make things more stable (and because verifying the actual list of loaded plugins is outside of the operator scope), this PR just checks that the list fetched from the running app is a non-empty array. This is sufficient to make sure that the created application is up and running, from the operator perspective.
&mdash;
`make test-e2e` should pass.
=> ci: Make the nightly E2E tests more robust when testing the loaded plugins endpoint

.github/workflows/nightly.yaml
This includes the 'release-1.4' branch in the E2E Nightly checks
&mdash;
=> ci: Include the 'release-1.4' branch in the E2E Nightly checks

.github/workflows/nightly-upgrade-test.yaml, tests/e2e/e2e_upgrade_test.go, tests/e2e/testdata/rhdh-operator-1.3.yaml, tests/e2e/testdata/rhdh-operator-1.4.yaml
With the new release-1.4 branch, we now have more possible upgrade combinations.
This PR moves the upgrade checks to a dedicated Workflow, and makes this matrix more maintainable.
- Fixes https://issues.redhat.com/browse/RHIDP-2641
See examples of runs here:
- E2E: https://github.com/rm3l/redhat-developer-hub-operator/actions/runs/12048172396
- E2E upgrade: https://github.com/rm3l/redhat-developer-hub-operator/actions/runs/12048174593
=> ci: Make logic for testing the operator upgrade paths extensible [RHIDP-2641]

bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml, config/profile/rhdh/manager.yaml
See PR title.
- Relates to https://issues.redhat.com/browse/RHIDP-2387
- Relates to https://github.com/redhat-developer/rhdh-operator/pull/450
=> Add missing `RELATED_IMAGE_*` env vars to the `rhdh` profile

.github/renovate.json
Temporarily add config to prevent [immortal PRs ](https://docs.renovatebot.com/key-concepts/pull-requests/#how-to-fix-immortal-prs) from re-opening.  Needed to clean out older renovate PRs
=> chore(renovate): temporarily quiet immortal PRs

.github/renovate.json
Some of the existing rules were disabling patch updates.  This allowed minor updates on Z stream branches which caused incorrect and (immortal) PRs to be created.   I also updated some of the `baseBranches` configs to use [matchBaseBranches](https://docs.renovatebot.com/configuration-options/#matchbasebranches) which is more applicable to package rules.  
I tested similar renovate configs on my own repo.  I think these [PRs](https://github.com/kim-tsao/operator-renovate/pulls) are more inline with what we want.  Note, we don't seem to be getting image update PRs in the maintenance releases and I think it's because we're disabling digest pinning.
=> chore(renovate): fix some rules

.rhdh/bundle/manifests/rhdh-operator.csv.yaml, bundle/manifests/backstage-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml
https://issues.redhat.com/browse/RHIDP-4687
=> chore(update): Updating Channel to trigger an Operator Update

.github/renovate.json
As the title suggests, this PR instructs Renovate to run `go mod tidy` after every dependency update, to make sure the `go.sum` file is consistent.
&mdash;
More details at https://docs.renovatebot.com/modules/manager/gomod/#post-update-options
/cc @kim-tsao
=> chore(renovate): Run `go mod tidy` after each Renovate update

bundle/backstage.io/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/rhdh-default-config_v1_configmap.yaml, config/profile/rhdh/default-config/deployment.yaml
This aligns with the changes in the Helm Chart - see https://github.com/redhat-developer/rhdh-chart/pull/50
Startup probe settings seem to have been added in the upstream Backstage Chart
in [1], but the current settings do not allow the liveness probe to be triggered sufficiently enough for the app to be
considered live.
This adjusts such settings by accounting for the worst-case scenario where the application might take a bit long to start.
This also aligns the probe endpoints with the Helm chart.
[1] https://github.com/backstage/charts/pull/216
- Relates to https://github.com/redhat-developer/rhdh-chart/pull/50
- Relates to [issues.redhat.com/browse/RHIDP-5106](https://issues.redhat.com/browse/RHIDP-5106)
- Relates to [issues.redhat.com/browse/RHIDP-4968](https://issues.redhat.com/browse …
=> fix: adjust startup, liveness and readiness probes settings

bundle/backstage.io/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/rhdh-default-config_v1_configmap.yaml, config/profile/rhdh/default-config/deployment.yaml
Manual cherry-pick of #564 
- Relates to https://github.com/redhat-developer/rhdh-chart/pull/50
- Relates to [issues.redhat.com/browse/RHIDP-5106](https://issues.redhat.com/browse/RHIDP-5106)
- Relates to [issues.redhat.com/browse/RHIDP-4968](https://issues.redhat.com/browse/RHIDP-4968)
=> fix: adjust startup, liveness and readiness probes settings (release-1.4)

.rhdh/bundle/manifests/rhdh-operator.clusterserviceversion.yaml, Makefile, bundle/backstage.io/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml, config/profile/backstage.io/kustomization.yaml, config/profile/rhdh/kustomization.yaml
=> chore: tagRelease.sh: bump to 1.4.1 in release-1.4 branch

.rhdh/bundle/manifests/rhdh-operator.csv.yaml, Makefile, bundle/manifests/backstage-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml
=> chore: tagRelease.sh: bump to 1.3.4 in release-1.3 branch

.github/workflows/pr-bundle-diff-checks.yaml, .github/workflows/pr-container-build.yaml
Checking out the PR fork repo could sometimes cause the "git diff" command to return an invalid revision range, like in [1].
This might happen if the fork repo is outdated.
To overcome this, this PR checks out the merge commit instead. That's also what GH does by default.
[1] https://github.com/redhat-developer/rhdh-operator/actions/runs/12417737622/job/34715972414?pr=582
https://github.com/redhat-developer/rhdh-operator/actions/runs/12417737622/job/34715972414?pr=582
I wanted to review and test #582 but realized no container was built for it. Based on the changes in that PR, it should have containers built.
We need to merge this first to see it in action and validate the behavior.
=> ci: Fix issue that could skip PR container builds if the fork repo is outdated

tests/e2e/testdata/rhdh-operator-1.3.yaml, tests/e2e/testdata/rhdh-operator-1.4.yaml
The tags used in the test seem to have expired from quay.io/rhdh-community/operator
https://github.com/redhat-developer/rhdh-operator/actions/workflows/nightly-upgrade-test.yaml
`make test-e2e-upgrade`  should pass
=> ci: Fix the E2E nightly upgrade tests

api/v1alpha1/zz_generated.deepcopy.go, api/v1alpha2/zz_generated.deepcopy.go, api/v1alpha3/zz_generated.deepcopy.go, bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/rhdh-default-config_v1_configmap.yaml, config/profile/rhdh/default-config/deployment.yaml, docs/configuration.md, integration_tests/rhdh-config_test.go, pkg/model/deployment.go, pkg/model/pvcs.go, pkg/model/pvcs_test.go, pkg/model/runtime.go, pkg/model/testdata/multi-pvc-containers.yaml, pkg/model/testdata/multicontainer-deployment.yaml, pkg/utils/pod-mutator.go, pkg/utils/utils.go, pkg/utils/utils_test.go
https://issues.redhat.com/browse/RHIDP-4595
=> Configure other than Backstage container to mount PVC volume to

.github/workflows/pr-bundle-diff-checks.yaml
Checking out the merge commit causes us to no longer be on the PR branch, as we can see in these logs [1].
[1] https://github.com/redhat-developer/rhdh-operator/actions/runs/12632058905/job/35222737737
This is to fix the CI issues detected in #622.
=> ci: Fix issue preventing the bundle diff checker job from committing changes detected

internal/controller/preprocessor_test.go, internal/controller/spec_preprocessor.go
Added sort for external config data for hash consistency
https://issues.redhat.com/browse/RHIDP-5411
=> Sort external config data for hash consistency (fix for RHIDP-5411)

.github/renovate.json
1.2 is now EOL with the release of 1.4. This PR updates the Renovate config so we don't get any dependency update PRs against that branch.
&mdash;
Not tested - we'll monitor the repo once this PR is merged
=> chore(renovate): Remove EOL 1.2.x from the Renovate config

README.md, docs/configuration.md, examples/showcase-config.yaml
chore: migrate from janus showcase to gh/rhd/rhdh and quay.io/rhdh-community/rhdh (RHIDP-1022)
N/A
N/A
=> chore: migrate from janus showcase to gh/rhd/rhdh and quay.io/rhdh-community/rhdh (RHIDP-1022)

.github/workflows/next-container-build.yaml, .github/workflows/pr-container-build.yaml, .github/workflows/pr.yaml
In some cases, for some reason, no change would be detected.
This was noticed in several PRs where, for example, container images should have been built but were skipped because the diff was being executed against the base commit at the time the PR was created, with errors similar to the following in the logs [1]:
```
fatal: Invalid revision range 5df8826c3b5e2c1d8c8f782fa616b19efd83330c..5f054315e9139f6098d7a84658c1e066987de045
Changed files for this commit:
==============================
==============================
```
This should hopefully fix that behavior, by delegating to https://github.com/tj-actions/changed-files.
The way the exclusion and inclusion rules are defined also makes the Workflows much more legible.
[1] https://github.com/redhat-developer/rhdh-operator/actions/runs/12 …
=> ci: Fix the changed files detection when running some of the Workflows

.github/workflows/next-container-build.yaml, .github/workflows/pr-container-build.yaml
This extracts the target repository as action secrets or variables,
so that forks can choose where to push the images.
This way, this workflow should pass in forks if configured properly.
It should also help fix the CI issues seen in #617 
https://github.com/redhat-developer/rhdh-operator/actions/runs/12711265573/job/35434216620?pr=617#step:8:422
=> ci: Fix container image build workflows running from forks

.rhdh/scripts/install-rhdh-catalog-source.sh
I added a flag to set the Install plan approval for the Subscription.
The default value is set to automatic for backward compatibility
- Fixes (contributes to) #https://issues.redhat.com/browse/RHIDP-2914
-
=> add Update-Strategy for the Subscription

bundle/backstage.io/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml, config/manager/deployment.yaml
Sets the readOnlyRootFilesystem option for the container securityContext to true.
https://issues.redhat.com/browse/RHIDP-5762
=> chore: set readOnlyRootFilesystem on Operator Container

.github/workflows/scripts-checks.yaml, .rhdh/scripts/prepare-restricted-environment.sh
This introduces ShellCheck for checking our scripts (including the CI and airgap ones) in CI.
It leverages https://github.com/redhat-plumbers-in-action/differential-shellcheck
- Fixes https://issues.redhat.com/browse/RHIDP-5162
=> ci: Check install and airgap scripts in CI [RHIDP 5162]

bundle/backstage.io/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/rhdh-default-config_v1_configmap.yaml, config/profile/rhdh/default-config/deployment.yaml, integration_tests/rhdh-config_test.go
Sets the readOnlyRootFilesystem:true on the initContainer, has been tested with 1.3.x, 1.4.x, and next images
https://issues.redhat.com/browse/RHIDP-5887
=> Make initContainer root filesystem read-only

.rhdh/docs/airgap.adoc, .rhdh/scripts/prepare-restricted-environment.sh
This introduces a new '--ci-index' option, which, when set to 'true', will replace all references to the internal Red Hat registries with quay.io when extracting and rebuilding the catalog.
- Addendum to https://issues.redhat.com/browse/RHIDP-5230
Example usage:
```sh
.rhdh/scripts/prepare-restricted-environment.sh \
--index-image quay.io/rhdh/iib:next-v4.18-x86_64 \
--ci-index true \
--filter-versions '*' \
--to-registry registry.localhost:5000/my-ns
```
=> chore: Make the airgap script work with CI index images

.github/workflows/nightly-upgrade-test.yaml, .github/workflows/nightly.yaml, .github/workflows/pr-bundle-diff-checks.yaml, Makefile, api/v1alpha1/zz_generated.deepcopy.go, api/v1alpha2/zz_generated.deepcopy.go, api/v1alpha3/zz_generated.deepcopy.go, bundle/backstage.io/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml, dist/backstage.io/install.yaml, dist/rhdh/install.yaml, tests/e2e/testdata/rhdh-operator-1.3.yaml, tests/e2e/testdata/rhdh-operator-1.4.yaml, tests/e2e/testdata/rhdh-operator-1.5.yaml
This includes `release-1.5` to the branches to be checked in the nightly workflows.
&mdash;
=> ci: Add `release-1.5` to the nightly checks

.github/workflows/scripts-checks.yaml, .gitignore, .rhdh/docs/airgap.adoc, .rhdh/scripts/prepare-restricted-environment.sh
Cherry-picks of the following PRs into `release-1.4`:
- #705
- #751
- #779
Relates to https://issues.redhat.com/browse/RHIDP-4415
See #705 
/cc @nickboldt
=> chore(release-1.4): Cherry-pick the improvements to the airgap env preparation script

bundle/backstage.io/manifests/backstage-default-config_v1_configmap.yaml, bundle/backstage.io/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/rhdh-default-config_v1_configmap.yaml, config/profile/backstage.io/default-config/app-config.yaml, config/profile/rhdh/default-config/app-config.yaml, config/profile/rhdh/default-config/dynamic-plugins.yaml, dist/backstage.io/install.yaml, dist/rhdh/install.yaml
As seen several times on #forum-rhdh, some people used to manually edit the default app-config/dynamic-plugins ConfigMaps created by the Operator in the cluster and were surprised that they lost their changes.
This PR clarifies that by adding a warning in these default ConfigMaps and providing reference links for customizing their configuration.
&mdash;
=> chore: Add warning comment advising against editing the default ConfigMaps manually in the cluster

.github/workflows/pr-bundle-diff-checks.yaml
For context, because we are pushing using the GITHUB_TOKEN token,
GH prevents triggering subsequent workflows. See [1] and [2].
[1] https://github.com/orgs/community/discussions/25702#discussioncomment-3248819
[2] https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#workarounds-to-trigger-further-workflow-runs
&mdash;
=> ci: Add instructions on how to manually unblock stuck PRs after the bundle changes have been pushed

bundle/backstage.io/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/rhdh-default-config_v1_configmap.yaml, config/profile/rhdh/default-config/deployment.yaml, dist/rhdh/install.yaml
Enables the readOnlyRootFilesystem option on the backend container by default for RHDH 1.6
https://issues.redhat.com/browse/RHIDP-5893
=> chore: enableReadOnlyRootFilesystem by default on backend container

.rhdh/scripts/prepare-restricted-environment.sh
chore(yq): update prepare-restricted-environment.sh to support use on machines where yq (jq python wrapper) is already installed (optionally, install the mikefarah yq to ~/.local/bin); 
also update defaults from 1.3/1.4 to 1.4/1.5 now that 1.3 is EOL; 
set default OCP to 4.18 as that's the latest EOL version
Signed-off-by: rhdh-bot service account <rhdh-bot@redhat.com>
N/A
https://issues.redhat.com/browse/RHIDP-4415
N/A
=> chore(yq): update prepare-restricted-environment.sh to support installing mikefarah yq

.github/workflows/pr.yaml
We need to 'make install' first, so that the necessary tool binaries (like controller-gen) can be downloaded locally.
Otherwise (because 'make install run' was started in the background),
we might end up with a race condition where the tool binary is not yet downloaded,
but the `make test` command
in the subsequent step tries to use it.
https://github.com/redhat-developer/rhdh-operator/actions/runs/14248198068/job/39934383296?pr=985
=> ci: Fix possible failures to find tool binaries (like `controller-gen`) in the test workflow

.rhdh/scripts/install-rhdh-catalog-source.sh
Otherwise, running a command like:
```
./install-rhdh-catalog-source.sh -v 1.5 --install-operator test-new
```
would fail with the following error:
```
constraints not satisfiable: no operators found in package test-new in the catalog referenced by subscription test-new, subscription test-new exists
```
- Fixes https://issues.redhat.com/browse/RHIDP-6408
Running this command should install the Operator:
```
./install-rhdh-catalog-source.sh -v 1.5 --install-operator test-new
```
=> chore(CI install script): Hardcode the package name to `rhdh` in the Subscription, unless a custom Catalog Source is specified

.rhdh/scripts/install-rhdh-catalog-source.sh
Because OLM expects only a single Operator Group per namespace, it will refuse to install the Operator,
with a `MultipleOperatorGroupsFound` like so:
```
{"level":"info","ts":"2025-03-13T09:58:15Z","logger":"controllers.adoption","msg":"Could not find Subscription","request":{"name":"sk-op","namespace":"rhdh-operator"}}
time="2025-03-13T09:59:27Z" level=warning msg="fail to upgrade operator group status og=rhdh-operator-group with condition {Type:MultipleOperatorGroup Status:True ObservedGeneration:0 LastTransitionTime:0001-01-01 00:00:00 +0000 UTC Reason:MultipleOperatorGroupsFound Message:Multiple OperatorGroup found in the same namespace}: OperatorGroup.operators.coreos.com \"rhdh-operator-group\" is invalid: lastUpdated: Required value" namespace=rhdh-operator …
```
=> chore(CI install script): Fail early if the `rhdh-operator` namespace already has some unexpected Operator Groups

.rhdh/scripts/install-rhdh-catalog-source.sh
This PR removes the catch-all mirrors from the ICSP resource created when running the install script on regular OCP clusters. 
It seems this is now forbidden on clusters like OSD, because it would reportedly conflict with system registries.
Error message seen from the cluster, for reference:
```
Error from server (Forbidden): error when creating "/tmp/tmp.aIrEtibjvz/ImageContentSourcePolicy_quay.io.yml": admission webhook "imagecontentpolicies-validation.managed.openshift.io" denied the request: Managed OpenShift customers may not create ImageContentSourcePolicy, ImageDigestMirrorSet, or ImageTagMirrorSet resources that configure mirrors that would conflict with system registries (e.g. quay.io, registry.redhat.io, registry.access.redhat.com, etc). For more details, see …
```
=> fix(install script): Avoid catch-all mirrors in the ICSP resource when installing CI builds of the Operator on regular OCP clusters [RHIDP-7177]

.github/workflows/nightly.yaml
sealights integration specific to rhdh-operator nightly run
- Fixes RHIDP-7360
Before merge please add SEALIGHTS_AGENT_TOKEN to repo secrets.
Tested on my forked branch
`if: ${{ matrix.branch == 'main' }}` is added to sealights steps to run only on main for now and not any other release branches as it overwrites the records with latest run.
=> RHIDP-7360 added sealights steps

.github/workflows/nightly.yaml
Incorporated Unit and Integration test runs also into nightly
- Fixes #_RHIDP-7360_
This is followup after first iteration of sealights integration to nightly workflow.
Trigger manual run to test after PR merged and observe the results on SeaLights Dashboard
=> incorporate unit and integration tests into nightly

OWNERS
Follow-up to https://github.com/redhat-developer/rhdh-operator/pull/1243
Actually set all members of the Install group as reviewers, as the Prow bot would request reviewers from people in the `reviewers` section.
&mdash;
=> chore: Update OWNERS with all members of the Install group

.github/workflows/nightly-upgrade-test.yaml, .github/workflows/nightly.yaml, .github/workflows/pr.yaml, Makefile, examples/bs-existing-secret.yaml, examples/filemounts.yaml, examples/raw-runtime-config.yaml, examples/rhdh-cr-with-app-configs.yaml, examples/rhdh-cr.yaml, tests/e2e/e2e_suite_test.go, tests/e2e/e2e_test.go, tests/e2e/testdata/rhdh-operator-1.5.yaml, tests/helper/helper_backstage.go, tests/helper/utils.go
This attempts to fix the nightly tests that have been failing for quite some time. I've narrowed it down to some flakiness in the Minikube action when the ingress add-on is enabled.
To alleviate this, this PR switches to a Kind cluster instead (similar to what is done in the [rhdh-chart repo](https://github.com/redhat-developer/rhdh-chart/blob/main/.github/workflows/test.yaml#L70-L91)).
- Fixes https://issues.redhat.com/browse/RHIDP-7804
Examples of runs:
- https://github.com/rm3l/redhat-developer-hub-operator/actions/runs/15584248268
- https://github.com/rm3l/redhat-developer-hub-operator/actions/runs/15584273681/job/43886544000
`make test-e2e` should pass on both OCP and vanilla K8s.
=> ci: Fix the nightly tests [RHIDP-7804]

.github/workflows/nightly.yaml
From the logs, it looks like the controller started for integration tests is not properly stopped and conflicts with the one running for E2E tests [1].
[1] https://productionresultssa12.blob.core.windows.net/actions-results/7d924262-805c-4c33-a236-d2af213adaf7/workflow-job-run-d9695c50-5212-5615-927a-64756a6a3e49/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-06-12T07%3A30%3A24Z&sig=MIxs%2FAa2pzV6urQXO9le0tblbTkB9ms%2B5v4EhiJTjPs%3D&ske=2025-06-12T16%3A52%3A35Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-06-12T04%3A52%3A35Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-05-05&sp=r&spr=https&sr=b&st=2025-06-12T07%3A20%3A19Z&sv=2025-05-05
- Relates to https://issues.redhat.com/browse/RHIDP-7804
=> ci(nightly): Run integration and E2E tests in separate test clusters [RHIDP-7804]

bundle/backstage.io/manifests/backstage-default-config_v1_configmap.yaml, bundle/backstage.io/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/rhdh-default-config_v1_configmap.yaml, config/profile/backstage.io/default-config/db-statefulset.yaml, config/profile/rhdh/default-config/db-statefulset.yaml, config/profile/rhdh/default-config/deployment.yaml, dist/backstage.io/install.yaml, dist/rhdh/install.yaml
This PR emoves the `replicas: 1` field from `config/profile/rhdh/default-config/deployment.yaml`.
This change allows users to apply Horizontal Pod Autoscalers (HPA) to the Backstage deployment without the operator reverting replica counts.
- Verified locally on Kind with metrics-server
- Confirmed HPA scales to 3 under CPU load
- Operator no longer resets to 1
You can view my entire replication of the issue and overall steps I took to ensure the fix works, in the issue comments section: https://issues.redhat.com/browse/RHIDP-7857
- Fixes https://issues.redhat.com/browse/RHIDP-7857
=> fix: remove default replicas value to support HPA scaling

.github/workflows/scripts-checks.yaml
For some reason, this dependency update is supposed to have fixed some
alerts that were displayed in Code Scanning. But these alerts seem to be
still relevant. So reverting so that the alerts can be reopened and so
that we can work on fixing those alerts (at least the most critical
ones).
This reverts commit 91f5b2c3f34be000c43be5088097296b073d3778.
Relates to https://issues.redhat.com/browse/RHIDP-6780
=> chore(deps): Revert "chore(deps): update redhat-plumbers-in-action/differential-shellcheck digest to 929381c (#1206)"

.rhdh/docker/Dockerfile, Dockerfile
Last time the runtime image was updated was... 5 months ago: https://github.com/redhat-developer/rhdh-operator/blame/release-1.6/.rhdh/docker/Dockerfile#L45
Updating the runtime image to 9.6 should be safe, as this is only used to run the operator binary copied from the builder image.
&mdash;
The images built from this PR should work as usual.
=> chore(deps): update ubi9-minimal runtime image to 9.6 and update go-toolset
