.github/workflows/next-container-build.yaml, .github/workflows/pr-container-build.yaml
chore: modify workflows to push to quay.io/rhdh
N/A
N/A
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)
=> chore: modify workflows to push to quay.io/rhdh

integration_tests/default-config_test.go
On real controller K8s control plane triggers reconciliation, so forcing it with TestBackstageReconciler does not work.
Fixed with adding extra annotation to make reconciliation happen
=> Fix the integration test for StatefulSet recreation on operator upgrade for real controller

.github/workflows/pr.yaml
Add integration tests on real cluster to pr.yaml workflow
=> Add integration tests on real cluster to pr.yaml workflow

.rhdh/bundle/manifests/rhdh-operator.csv.yaml, bundle/manifests/backstage-operator.clusterserviceversion.yaml, config/manifests/bases/backstage-operator.clusterserviceversion.yaml
chore(doc): switch to use the shared maintainer mailing list at rhdh-bot@redhat.com for contacting to ask questions about the operator
N/A
https://issues.redhat.com/browse/RHIDP-1960
N/A
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)
=> chore(doc): switch to use the shared mailing list RHIDP-1960

.rhdh/bundle/manifests/rhdh-operator.csv.yaml, Makefile, bundle/manifests/backstage-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml
=> chore: tagRelease.sh: bump to 1.4.0 in main branch

.rhdh/docker/Dockerfile
Signed-off-by:...
bump to newer base images
N/A
N/A
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)
=> bump to newer base images

docs/configuration.md
=> chore: fix app-config doc

OWNERS
Adding myself as an approver so I can handle renovate PRs.  No need to update `pr-container-build.yaml` because my id is already there (likely migrated from the old repo)
N/A
=> chore(owners): add kim-tsao to owners file

docs/profiles.md
Documentation for https://issues.redhat.com/browse/RHIDP-1338
=> Profiles documentation

.github/actions/docker-build/action.yaml, .github/renovate.json, .github/workflows/next-container-build.yaml, .github/workflows/nightly.yaml, .github/workflows/pr-bundle-diff-checks.yaml, .github/workflows/pr-container-build.yaml, .github/workflows/pr.yaml
…ranches
Related to work done in https://issues.redhat.com/browse/RHIDP-4031
=> chore: [release-1.3] backport github folder updates for new release branches

.rhdh/scripts/install-rhdh-catalog-source.sh
chore(ux): after installing catalog source, tell user where to go to install RHDH from operator
N/A
N/A
=> chore(ux): after installing catalog source, tell user where to go to install RHDH from operator

.rhdh/scripts/install-rhdh-catalog-source.sh
chore: use IDMS for next builds ([RHIDP-4223](https://issues.redhat.com/browse/RHIDP-4223))
N/A
N/A
=> chore: use IDMS for next builds (RHIDP-4223)

docker/Dockerfile
=> chore(deps): bump go-toolset container image

OWNERS
=> chore(): [release-1.3] Update OWNERS - add kim-tsao

docker/Dockerfile
=> chore(): revert go-toolset change

cmd/main.go, integration_tests/suite_test.go, internal/controller/backstage_controller.go, pkg/model/appconfig_test.go, pkg/model/configmapenvs_test.go, pkg/model/configmapfiles_test.go, pkg/model/db-secret_test.go, pkg/model/db-statefulset_test.go, pkg/model/deployment_test.go, pkg/model/dynamic-plugins_test.go, pkg/model/pvcs_test.go, pkg/model/route_test.go, pkg/model/runtime.go, pkg/model/runtime_test.go, pkg/model/secretfiles_test.go
Remove ownRuntime flag as it is not used
https://issues.redhat.com/browse/RHIDP-3609
=> chore: remove ownruntime flag

.rhdh/scripts/install-rhdh-catalog-source.sh
bump sample that deploys RHDH to alpha3
N/A
N/A
=> chore(doc, sample): bump sample that deploys RHDH to use api alpha3

.github/renovate.json
Manually cherry pick
https://issues.redhat.com/browse/RHIDP-5054
=> chore(renovate): 1.2.x update config

examples/rhdh-cr-with-app-configs.yaml
=> Fix replicas in example

Makefile, bundle/backstage.io/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml, config/profile/backstage.io/kustomization.yaml, config/profile/rhdh/kustomization.yaml
=> chore: tagRelease.sh: bump to 1.6.0 in main branch

bundle/backstage.io/manifests/backstage-operator.clusterserviceversion.yaml, bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml, config/rbac/role.yaml, dist/backstage.io/install.yaml, dist/rhdh/install.yaml, docs/configuration.md, integration_tests/matchers.go, integration_tests/rhdh-config_test.go, integration_tests/route_test.go, internal/controller/backstage_controller.go, internal/controller/spec_preprocessor.go, pkg/model/appconfig.go, pkg/model/externalconfig.go, pkg/model/route.go, pkg/model/route_test.go, pkg/model/runtime.go
Manual cherry-pick of #892
- Fixes https://issues.redhat.com/browse/RHIDP-6192
/assign
=> [release-1.6] feat: Auto-detect the OCP ingress domain and populate the baseUrls in the default app-config ConfigMap [RHIDP-6192]

.rhdh/bundle/manifests/rhdh-operator.clusterserviceversion.yaml
Signed-off-by:...
chore: bump to 1.4.3 in CSV
N/A
N/A
=> chore: bump to 1.4.3 in CSV

.github/workflows/nightly-upgrade-test.yaml, .github/workflows/nightly.yaml, tests/e2e/e2e_test.go, tests/e2e/e2e_upgrade_test.go
Includes release-1.6 in the nightly checks and attempts to fix the tests as well.
&mdash;
=> ci: Include 1.6 in the nightly checks

.rhdh/docker/Dockerfile, Dockerfile
`make image-build`
```
1 warning found (use docker --debug to expand):
- UndefinedVar: Usage of undefined variable '$EXTERNAL_SOURCE' (line 59)
```
=> chore: add ENV EXTERNAL_SOURCE to Dockerfile

.github/workflows/nightly.yaml
sealights integration specific to rhdh-operator nightly run
Additional release branches included in this pr as part of nightly
- Fixes RHIDP-7360
This is following the merge of PR #1136
=> sealights integration nightly run enabling release branches also

tests/e2e/e2e_test.go
No need to go that deep into testing the access to the metric endpoints based on SA authorization. This should be guaranteed by the controller-runtime library.
What really should matter here is making sure that the controller pod does not have the kube-rbac-proxy sidecar container in it (due to its deprecation and security concerns).
- Relates to https://issues.redhat.com/browse/RHIDP-4236
- Relates to https://github.com/redhat-developer/rhdh-operator/actions/runs/15068775392/job/42359609956
=> ci: Simplify the metrics endpoint E2E test

.github/workflows/pr.yaml
Steps to incorporate SeaLights integration
For Reference previous PR closed: https://github.com/redhat-developer/rhdh-operator/pull/1107
- Fixes #_RHIDP-7359_
This has same steps as nightly workflow which got merged. Just need to test the steps in this workflow.
=> SL steps to pr workflow

.github/workflows/pr.yaml
Follow-up to #1218
Fixes CI issues like https://github.com/redhat-developer/rhdh-operator/actions/runs/15419615988/job/43390939527?pr=1222
=> ci: Fix checkout step in pr.yaml workflow

.github/workflows/pr.yaml
Some expensive steps are executed but should not, based on the files changed.
&mdash;
=> ci(pr.yaml): Skip some expensive steps if not needed

.github/workflows/nightly.yaml
Follow-up to #1260 and #1257
- Relates to https://issues.redhat.com/browse/RHIDP-7804
=> ci(nightly): Test app access via port-forwarding instead [RHIDP-7804]

docs/orchestrator.md, examples/orchestrator.yaml
Applying examples/orchestrator.yaml failed
https://issues.redhat.com/browse/RHDHBUGS-1913
with installed on Openshift RHDH 1.7 try:
`oc apply -f example/orchestrator.yaml -n <your-namespace>
`
=> fix orchestrator.yaml example and documentation (release-1.7)

.rhdh/docker/Dockerfile, Dockerfile
- Fixes [RHIDP-8620](https://issues.redhat.com/browse/RHIDP-8620)
=> chore: Update from ubi9/go-toolset:9.6-1754467841 to ubi9/go-toolset:9.6-1755529097

.rhdh/docker/Dockerfile, Dockerfile, bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml, config/manager/deployment.yaml, config/profile/rhdh/patches/deployment-patch.yaml
=> add labels to controller deployment for discoverability
